stages:
  stages01:
    cmd: python stage_01.py
    deps:
      - stage_01.py
    outs:
      - artifacts01.txt
  stages02:
    cmd: python stage_02.py
    deps:
      - artifacts01.txt
      - stage_02.py

  last_stage:
    cmd: python stage_03.py
    deps:
      - artifacts01.txt
      - stage_03.py
    outs:
      - artifacts02.txt
  
